version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      # Optionally mount themes or uploads as needed
    env_file:
      - .env

  ci-runner:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - db
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./ci.sh:/ci.sh
    working_dir: /var/www/html/wp-content/plugins/wp-qr-trackr
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    entrypoint: ["/bin/bash", "/ci.sh"]

volumes:
  db_data: 