services:
  wordpress-nonprod:
    image: wordpress:latest
    ports:
      - "8081:80" # Nonprod environment runs on port 8081
    environment:
      WORDPRESS_DB_HOST: db-nonprod:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    depends_on:
      - db-nonprod
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    # No plugin code mount: upload via admin UI for clean testing

  db-nonprod:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: rootpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data_nonprod:/var/lib/mysql

  ci-runner:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      db-nonprod:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db-nonprod:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data_nonprod:
    # Persistent database storage 