# This file is for CI/CD environments (GitHub Actions).
# It overrides the ci-runner service to use a pre-built image from GHCR.
services:
  db-nonprod:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  ci-runner:
    image: ghcr.io/solidsystems/wp-qr-trackr/ci-runner:${CI_IMAGE_TAG:-main}
    depends_on:
      db-nonprod:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db-nonprod:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - .:/usr/src/app
      - ./vendor:/usr/src/app/vendor
      - ./node_modules:/usr/src/app/node_modules 