services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

  ci-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ci
    working_dir: /usr/src/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # If you need a DB, define a minimal db service and update these vars accordingly
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      CI: 1
    volumes:
      # Only mount specific files needed for CI, not the entire directory
      - ../composer.json:/usr/src/app/composer.json:ro
      - ../composer.lock:/usr/src/app/composer.lock:ro
      - ../package.json:/usr/src/app/package.json:ro
      - ../yarn.lock:/usr/src/app/yarn.lock:ro
      - ../wp-content:/usr/src/app/wp-content:ro
      - ../includes:/usr/src/app/includes:ro
      - ../templates:/usr/src/app/templates:ro
      - ../wp-qr-trackr.php:/usr/src/app/wp-qr-trackr.php:ro
      - ../config:/usr/src/app/config:ro
      - ../scripts:/usr/src/app/scripts:ro
      - ../ci.sh:/usr/src/app/ci.sh:ro
      - ~/.config/gh:/root/.config/gh
