services:
  wordpress-nonprod:
    image: wordpress:latest
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db-nonprod:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://localhost:8081');
        define('WP_SITEURL','http://localhost:8081');
        define('WP_ENVIRONMENT_TYPE','nonprod');
      WORDPRESS_ADMIN_USER: trackr
      WORDPRESS_ADMIN_PASSWORD: trackr
      WORDPRESS_ADMIN_EMAIL: nonprod@example.com
      WORDPRESS_SKIP_INSTALL: "no"
    depends_on:
      db-nonprod:
        condition: service_healthy
    volumes:
      - wordpress_data_nonprod:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - ../wp-content/plugins/wp-qr-trackr:/var/www/html/wp-content/plugins/wp-qr-trackr

  wpcli-nonprod:
    image: wordpress:cli
    depends_on:
      wordpress-nonprod:
        condition: service_started
      db-nonprod:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db-nonprod:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
      WP_HOME: http://localhost:8081
      WP_SITEURL: http://localhost:8081
    volumes:
      - wordpress_data_nonprod:/var/www/html
      - ../wp-content/plugins/wp-qr-trackr:/var/www/html/wp-content/plugins/wp-qr-trackr
      - ./php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    entrypoint: ["tail", "-f", "/dev/null"]

  db-nonprod:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: rootpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data_nonprod:/var/lib/mysql

volumes:
  db_data_nonprod:
  wordpress_data_nonprod: 