<?php
/**
 * Admin list page template for QR Code Links.
 *
 * @package WP_QR_TRACKR
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

// Expect $list_table to be prepared by caller (qrc_admin_page()).
?>
<div class="wrap">
	<h1 class="wp-heading-inline"><?php esc_html_e( 'QR Code Links', 'wp-qr-trackr' ); ?></h1>
	<a href="<?php echo esc_url( admin_url( 'admin.php?page=qr-code-add-new' ) ); ?>" class="page-title-action"><?php esc_html_e( 'Add New', 'wp-qr-trackr' ); ?></a>
	<a href="<?php echo esc_url( wp_nonce_url( admin_url( 'admin.php?page=qr-code-links&action=regenerate' ), 'regenerate_qr_codes' ) ); ?>" class="page-title-action" onclick="return confirm('<?php echo esc_js( __( 'This will regenerate all QR codes with tracking URLs. Continue?', 'wp-qr-trackr' ) ); ?>');"><?php esc_html_e( 'Regenerate QR Codes', 'wp-qr-trackr' ); ?></a>
	<hr class="wp-header-end" />

	<style>
		/* Move the built-in displaying-num from .tablenav to a custom row */
		.qrc-display-count { text-align: right; margin: 8px 0 12px; color: #50575e; }
	</style>

	<form method="get">
		<input type="hidden" name="page" value="qr-code-links" />
		<?php
			ob_start();
			$list_table->display();
			$table_html = ob_get_clean();
		?>
		<?php
		// Extract the default displaying-num markup and re-render it below filters.
		$count_text = '';
		if ( preg_match( '/<span class="displaying-num">([^<]+)<\/span>/i', $table_html, $m ) ) {
			$count_text = trim( wp_strip_all_tags( $m[1] ) );
			// Remove all original displaying-num to avoid duplicates (handles top and bottom navs).
			$table_html = preg_replace( '/<span class="displaying-num">[^<]+<\/span>/i', '', $table_html );
		}
		?>
		<?php if ( $count_text ) : ?>
			<div class="qrc-display-count"><?php echo esc_html( $count_text ); ?></div>
		<?php endif; ?>
		<?php echo $table_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Safe HTML generated by WP_List_Table with displaying-num removed. ?>
	</form>
</div>
