name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build CI Container
        run: docker compose build --no-cache ci-runner

      - name: Run All CI Checks
        run: docker compose run --rm ci-runner 