name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run All CI Checks
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm ci-runner 