name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-php:
    name: PHP Lint & Standards
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.4]
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, xdebug
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: PHP_CodeSniffer (WordPress)
        run: |
          composer install --prefer-dist --no-progress
          cd wp-content/plugins/wp-qr-trackr
          ../../../vendor/bin/phpcs --standard=../../../.phpcs.xml --report=full --extensions=php --warning-severity=0 .
      - name: PHP_CodeSniffer (Tests Only)
        run: |
          composer install --prefer-dist --no-progress
          cd wp-content/plugins/wp-qr-trackr
          ../../../vendor/bin/phpcs --standard=../../../.phpcs.xml --report=full --extensions=php --warning-severity=0 tests

  lint-js:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install JS dependencies
        run: yarn install
        working-directory: wp-content/plugins/wp-qr-trackr
      - name: Run ESLint
        run: yarn lint
        working-directory: wp-content/plugins/wp-qr-trackr

  lint-css:
    name: CSS Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install JS dependencies
        run: yarn install
        working-directory: wp-content/plugins/wp-qr-trackr
      - name: Run Stylelint
        run: yarn stylelint
        working-directory: wp-content/plugins/wp-qr-trackr

  test-phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.4]
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, xdebug
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --configuration=wp-content/plugins/wp-qr-trackr/phpunit.xml --coverage-clover=wp-content/plugins/wp-qr-trackr/coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./wp-content/plugins/wp-qr-trackr/coverage.xml
        continue-on-error: true

  audit-deps:
    name: Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: Composer Audit
        run: composer audit || true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install JS dependencies
        run: yarn install
        working-directory: wp-content/plugins/wp-qr-trackr
      - name: Yarn Audit
        run: yarn audit --groups dependencies --level moderate || true

  build-docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker compose build 