name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
          tools: composer:v2, phpcs, phpstan

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          composer require --dev squizlabs/php_codesniffer wp-coding-standards/wpcs phpstan/phpstan

      - name: Run PHPCS
        run: |
          ./vendor/bin/phpcs --standard=.phpcs.xml wp-content/plugins/wp-qr-trackr/

      - name: Run PHPStan
        run: |
          ./vendor/bin/phpstan analyse wp-content/plugins/wp-qr-trackr/ --level=5

      - name: Run WordPress Security Scanner
        run: |
          composer require --dev wp-cli/wp-cli-bundle
          ./vendor/bin/wp plugin verify-checksums wp-qr-trackr
          ./vendor/bin/wp plugin check wp-qr-trackr

      - name: Run ESLint
        run: |
          yarn install
          yarn lint

      - name: Run Stylelint
        run: |
          yarn stylelint

  lint-php:
    name: PHP Lint & Standards
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.4]
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, xdebug
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: PHP_CodeSniffer (WordPress)
        run: |
          composer install --prefer-dist --no-progress
          cd wp-content/plugins/wp-qr-trackr
          ../../../vendor/bin/phpcs --standard=../../../.phpcs.xml --report=full --extensions=php --warning-severity=0 .
      - name: PHP_CodeSniffer (Tests Only)
        run: |
          composer install --prefer-dist --no-progress
          cd wp-content/plugins/wp-qr-trackr
          ../../../vendor/bin/phpcs --standard=../../../.phpcs.xml --report=full --extensions=php --warning-severity=0 tests

  lint-js:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install JS dependencies
        run: yarn install
        working-directory: wp-content/plugins/wp-qr-trackr
      - name: Run ESLint
        run: yarn lint
        working-directory: wp-content/plugins/wp-qr-trackr

  lint-css:
    name: CSS Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install JS dependencies
        run: yarn install
        working-directory: wp-content/plugins/wp-qr-trackr
      - name: Run Stylelint
        run: yarn stylelint
        working-directory: wp-content/plugins/wp-qr-trackr

  test-phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.4]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, xdebug
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
      - name: Ensure clean test database
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "DROP DATABASE IF EXISTS wordpress_test; CREATE DATABASE wordpress_test;"
      - name: Install WordPress
        run: |
          wp core download --version=latest --path=wp
          wp config create --dbname=wordpress_test --dbuser=root --dbpass=root --dbhost=127.0.0.1 --path=wp
          wp db create --path=wp
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --configuration=wp-content/plugins/wp-qr-trackr/phpunit.xml --coverage-clover=wp-content/plugins/wp-qr-trackr/coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./wp-content/plugins/wp-qr-trackr/coverage.xml
        continue-on-error: true

  audit-deps:
    name: Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: Composer Audit
        run: composer audit || true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install JS dependencies
        run: yarn install
        working-directory: wp-content/plugins/wp-qr-trackr
      - name: Yarn Audit
        run: yarn audit --groups dependencies --level moderate || true

  build-docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker compose build 