name: Run PHPUnit tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-runner:latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wpdb
          MYSQL_USER: wpuser
          MYSQL_PASSWORD: wppass
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        php: [8.1, 8.2]
        wp: [6.4, latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Node.js dependencies
        run: |
          if [ -f package.json ]; then
            yarn install
          fi

      - name: Install SVN
        run: apt-get update && apt-get install -y subversion

      - name: Run WP-CLI scaffolded tests
        run: |
          bash scripts/install-wp-tests.sh wpdb wpuser wppass mysql ${{ matrix.wp }}
          ./vendor/bin/phpunit
