name: Release Plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.1)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Make build script executable
        run: chmod +x scripts/build-release.sh

      - name: Build and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: ./scripts/build-release.sh

# Prereleases (with -rcN) are supported and will be marked as prereleases on GitHub.
# To use email notifications, set the following secrets in your repo:
# SMTP_SERVER, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, RELEASE_EMAIL_TO, RELEASE_EMAIL_FROM 